-- Crear usuario del proyecto
CREATE USER django_grupo7 IDENTIFIED BY Grupo72025progra;
GRANT CONNECT, RESOURCE TO django_grupo7;

-- Tabla de roles
CREATE TABLE rol (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(30) UNIQUE NOT NULL
);

-- Tabla de usuarios 
CREATE TABLE usuario (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    username VARCHAR2(150) NOT NULL,
    email VARCHAR2(150) UNIQUE NOT NULL,
    password VARCHAR2(128) NOT NULL
);

-- Tabla de perfiles
CREATE TABLE perfil (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    rol_id NUMBER,
    telefono VARCHAR2(20),
    direccion VARCHAR2(200),
    fecha_nacimiento DATE,
    CONSTRAINT fk_perfil_user FOREIGN KEY (user_id) REFERENCES usuario(id),
    CONSTRAINT fk_perfil_rol FOREIGN KEY (rol_id) REFERENCES rol(id)
);

-- Tabla de productos
CREATE TABLE producto (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    descripcion CLOB,
    precio NUMBER(8,2) NOT NULL,
    stock NUMBER DEFAULT 0,
    imagen_url VARCHAR2(200)
);

-- Tabla de ítems en el carrito
CREATE TABLE carrito_item (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    producto_id NUMBER NOT NULL,
    cantidad NUMBER DEFAULT 1,
    CONSTRAINT fk_carrito_user FOREIGN KEY (user_id) REFERENCES usuario(id),
    CONSTRAINT fk_carrito_producto FOREIGN KEY (producto_id) REFERENCES producto(id)
);

-- Tabla de órdenes
CREATE TABLE orden (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    total NUMBER(10,2) NOT NULL,
    CONSTRAINT fk_orden_user FOREIGN KEY (user_id) REFERENCES usuario(id)
);

-- Tabla de detalles de orden
CREATE TABLE detalle_orden (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    orden_id NUMBER NOT NULL,
    producto_id NUMBER NOT NULL,
    cantidad NUMBER NOT NULL,
    precio_unitario NUMBER(8,2) NOT NULL,
    CONSTRAINT fk_detalle_orden FOREIGN KEY (orden_id) REFERENCES orden(id),
    CONSTRAINT fk_detalle_producto FOREIGN KEY (producto_id) REFERENCES producto(id)
);

-- Roles base
INSERT INTO rol (nombre) VALUES ('admin');
INSERT INTO rol (nombre) VALUES ('cliente');